/**
 * Browser-safe measure surface — no node:crypto / kernel.
 * Import from `@spds/geometry-contracts/measure` in client code.
 */
export {
  MeasureKindSchema,
  MeasureUnitSchema,
  MeasureProvenanceSchema,
  MeasureEngineSchema,
  MeasureRequestSchema,
  MeasureResultSchema,
  MeasureCompareResultSchema,
  BoxExtentsSchema,
  FACE_KEYS,
  boxFeaturePath,
  boxVertices,
  boxEdges,
  boxFaces,
  resolveBoxFeature,
  parseBoxFeaturePath,
  measureBoxFeatures,
  distanceMm,
  angleBetweenEdgesDeg,
  angleBetweenFacesDeg,
  angleBetweenDirectionsDeg,
  compareMeasureResults,
  defaultCompareTolerance,
  midpoint,
  type FaceKey,
  type MeasureKind,
  type MeasureUnit,
  type MeasureProvenance,
  type MeasureEngine,
  type MeasureRequest,
  type MeasureResult,
  type MeasureCompareResult,
  type BoxExtents,
  type BoxVertex,
  type BoxEdge,
  type BoxFace,
  type Vec3,
} from './measure.js';
export {
  triangleArea,
  faceAreaFromTriangleIndex,
  snapNearestVertex,
  snapNearestEdge,
  snapNearestFace,
  snapFaceByHitPoint,
  assertSemanticFeaturePath,
} from './measure-mesh.js';
