export {
  TOPOLOGY_DOMAINS,
  DesignTopologyKindSchema,
  ProductTopologyKindSchema,
  GeometricTopologyKindSchema,
  DesignTopologyNodeSchema,
  ProductTopologyNodeSchema,
  GeometricTopologyNodeSchema,
  TopologyNodeSchema,
  TopologyMappingSchema,
  parseTopologyNode,
  parseTopologyMapping,
  type TopologyDomain,
  type DesignTopologyNode,
  type ProductTopologyNode,
  type GeometricTopologyNode,
  type TopologyNode,
  type TopologyMapping,
} from './domains.js';
